name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Create workspace dirs
        run: |
          mkdir -p "$GITHUB_WORKSPACE/ipa/Payload"

      - name: Download DEB
        run: |
          curl -L "${{ inputs.deb }}" -o "$GITHUB_WORKSPACE/app.deb"

      - name: Extract DEB (data payload)
        run: |
          # -X extracts the data.tar.* payload into target dir
          dpkg-deb -X "$GITHUB_WORKSPACE/app.deb" "$GITHUB_WORKSPACE/app"

      - name: Validate app bundle exists
        run: |
          shopt -s nullglob
          APP_DIRS=("$GITHUB_WORKSPACE/app/Applications/"*.app)
          if [ ${#APP_DIRS[@]} -eq 0 ]; then
            echo "ERROR: No .app found in Applications/ (this DEB is likely a tweak, not an app)."
            exit 1
          fi

      - name: Build IPA structure
        run: |
          cp -R "$GITHUB_WORKSPACE/app/Applications/"*.app "$GITHUB_WORKSPACE/ipa/Payload/"
          cd "$GITHUB_WORKSPACE/ipa"
          # zip the Payload directory into an IPA at the repo root
          zip -r "$GITHUB_WORKSPACE/App.ipa" Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: ${{ github.workspace }}/App.ipa
